# Generated by Django 6.0.2 on 2026-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cum', models.CharField(max_length=50, unique=True)),
                ('nombre_generico', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=100)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('uso_indicado', models.TextField()),
                ('efectos_secundarios', models.TextField()),
                ('requiere_formula', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos',
            },
        ),
    ]
