# Generated by Django 6.0.5 on 2026-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, verbose_name='Face Encoding'),
        ),
    ]
