# Generated by Django 6.0.5 on 2026-06-29 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_medicamento'),
        ('epsinventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='epsinventario.eps', verbose_name='EPS asignada'),
        ),
    ]
