# Generated by Django 6.0.5 on 2026-06-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_usuario_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('eps', 'EPS')], default='cliente', max_length=20),
        ),
    ]
