# Generated by Django 6.0.5 on 2026-06-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_usuario_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='sede',
            field=models.CharField(choices=[('bogota_norte', 'Pharmony Bogotá Norte'), ('bogota_sur', 'Pharmony Bogotá Sur'), ('chapinero', 'Pharmony Chapinero'), ('medellin', 'Pharmony Medellín'), ('el_poblado', 'Pharmony El Poblado'), ('cali', 'Pharmony Cali'), ('barranquilla', 'Pharmony Barranquilla'), ('bucaramanga', 'Pharmony Bucaramanga'), ('pasto', 'Pharmony Pasto'), ('manizales', 'Pharmony Manizales'), ('villavicencio', 'Pharmony Villavicencio')], default='bogota_norte', max_length=50, verbose_name='Sede'),
        ),
    ]
