# Generated by Django 6.0.5 on 2026-06-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0004_medicamento_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
