# Generated by Django 6.0.5 on 2026-06-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_usuario_face_encoding'),
        ('Farmacia', '0005_actualizar_rol_farmaceutico_a_eps'),
    ]

    operations = [
    ]
