# Generated by Django 6.0.5 on 2026-07-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_medicamento_stock'),
        ('Farmacia', '0006_merge_20260629_1923'),
    ]

    operations = [
    ]
