# Generated by Django 6.0.5 on 2026-07-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0007_merge_0005_medicamento_stock_0006_merge_20260629_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock',
        ),
    ]
