# Generated by Django 6.0.5 on 2026-08-15 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0009_usuario_cedula_usuario_direccion'),
        ('epsinventario', '0002_sede_latitud_sede_longitud_solicitudmedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerechoPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(max_length=30, unique=True, verbose_name='Número de Radicado')),
                ('estado', models.CharField(choices=[('radicado', 'Radicado'), ('en_tramite', 'En Trámite'), ('entregado', 'Entregado por EPS (Resuelto)'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='radicado', max_length=20, verbose_name='Estado de la Petición')),
                ('fecha_radicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Radicación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta/Entrega')),
                ('observaciones_eps', models.TextField(blank=True, null=True, verbose_name='Observaciones de la EPS / Farmacéutico')),
                ('firestore_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firestore ID')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peticiones_gestionadas', to=settings.AUTH_USER_MODEL, verbose_name='Farmacéutico / Personal que atendió')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derechos_peticion', to='Farmacia.medicamento', verbose_name='Medicamento Reclamado')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derechos_peticion', to='epsinventario.sede', verbose_name='Sede donde acudió')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derechos_peticion', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Derecho de Petición',
                'verbose_name_plural': 'Derechos de Petición',
                'db_table': 'derechos_peticion',
                'ordering': ['-fecha_radicacion'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dosis / Frecuencia')),
                ('cantidad_prescrita', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad prescrita')),
                ('fuente_asignacion', models.CharField(choices=[('ia_formula', 'Escaneo IA (Fórmula Médica)'), ('eps_manual', 'Asignación EPS / Farmacéutico'), ('admin', 'Administrador')], default='ia_formula', max_length=20, verbose_name='Fuente de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Tratamiento Activo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('firestore_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firestore ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='Farmacia.medicamento', verbose_name='Medicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Medicamento Asignado a Paciente',
                'verbose_name_plural': 'Medicamentos Asignados a Pacientes',
                'db_table': 'medicamentos_usuario',
                'unique_together': {('usuario', 'medicamento')},
            },
        ),
    ]
