# Generated by Django 6.0.5 on 2026-08-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0006_turno_cantidad_entregada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='preparando', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='turnos.turno')),
            ],
        ),
    ]
