services:
  - type: web
    name: pharmony
    runtime: python
    plan: free
    rootDir: Pharmony
    buildCommand: "./build.sh"
    startCommand: "gunicorn PharmonyBase.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS_PATH
        value: "ServiceAccountKey.json"
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ESCANER_GEMINI_API_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@pharmony.local"
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

