# Generated by Django 6.0.5 on 2026-08-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmacia', '0009_usuario_cedula_usuario_direccion'),
        ('epsinventario', '0002_sede_latitud_sede_longitud_solicitudmedicamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('firestore_id', models.CharField(blank=True, max_length=100, null=True)),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='epsinventario.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('formula_medica', models.FileField(upload_to='turnos/formulas/')),
                ('cedula_ciudadania', models.FileField(upload_to='turnos/cedulas/')),
                ('direccion_envio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En atención'), ('correcto', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15)),
                ('motivo_estado', models.TextField(blank=True, null=True)),
                ('posicion_cola', models.PositiveIntegerField(default=0)),
                ('firestore_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('auxiliar_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='turnos.caja')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Farmacia.medicamento')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='epsinventario.sede')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='epsinventario.solicitudmedicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='turnos.turno')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuxiliarSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliares', to='epsinventario.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_habilitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'sede')},
            },
        ),
    ]
