# Generated by Django 6.0.5 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeturno',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='turnos/chat_adjuntos/'),
        ),
        migrations.AlterField(
            model_name='mensajeturno',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
