# Generated by Django 6.0.5 on 2026-08-09 19:06

import turnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_mensajeturno_archivo_alter_mensajeturno_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeturno',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='turnos/chat_adjuntos/', validators=[turnos.models.validar_extension_documento]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cedula_ciudadania',
            field=models.FileField(upload_to='turnos/cedulas/', validators=[turnos.models.validar_extension_documento]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='formula_medica',
            field=models.FileField(upload_to='turnos/formulas/', validators=[turnos.models.validar_extension_documento]),
        ),
    ]
