# Generated by Django 6.0.5 on 2026-08-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_mensajeturno_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
