# Generated by Django 6.0.5 on 2026-08-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turno_ciudad_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En atención'), ('correcto', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15),
        ),
    ]
