# Generated by Django 6.0.5 on 2026-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
