# Generated by Django 6.0.5 on 2026-08-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0009_usuario_cedula_usuario_direccion'),
        ('turnos', '0006_turno_cantidad_entregada'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cedula_detectada_ia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='medico_detectado_ia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente_detectado_ia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='resultado_ia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemEntregaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('indicaciones', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_turno', to='Farmacia.medicamento')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_entregados', to='turnos.turno')),
            ],
        ),
    ]
