# Generated by Django 6.0.5 on 2026-06-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmacia', '0002_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='epsinventario.eps')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=10)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='Farmacia.medicamento')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='epsinventario.sede')),
            ],
            options={
                'unique_together': {('sede', 'medicamento', 'lote')},
            },
        ),
    ]
