# Generated by Django 6.0.5 on 2026-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsinventario', '0002_sede_latitud_sede_longitud_solicitudmedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='atiende_fines_semana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sede',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
